version: "3.8"

services:
  frontend:
    build: ./frontend  # Path to your React app
    ports:
      - "5173:5173"  # Expose React app on port 5173
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network

  backend:
    build: ./backend  # Path to your Flask app
    ports:
      - "5000:5000"  # Expose Flask app on port 5000
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
